NetworkConfiguration/dhcpcd

src/logerr.h
The `__printflike` macro appears to take two arguments.
=> Fix build issue when `__GNUC__ <= 2`

src/dhcpcd.8.in
I noticed a few typos and such while reading this man page, so I thought I'd fix them. (Thanks for creating dhcpcd!)
=> dhcpcd.8.in: Fix typos and minor grammatical issues

hooks/30-hostname
I tried sending you the patch via email but it got rejected:
```
roy@marples.name
host dash.servers.dxld.at [82.199.155.50]
SMTP error from remote mail server after RCPT TO:<roy@marples.name>:
550 Administrative prohibition
```
Is that intentional or is my mail server config broken?
=> 30-hostname: Fix typo: hsort -> hshort

configure
The dbdir option is used to specify the location of the DHCPd database.  The default /var/db is not FHS compliant so some may wish to change this to
=> Added documentation for undocumented option

src/if-linux.c
musl has its own definition of struct ethhdr, so only include netinet/if_ether.h on systems with GLIBC.  For the ARPHDR constants, we must include linux/if_arp.h instead.
This patch was used downstream in https://github.com/void-linux/void-packages/pull/15616.
=> Fix building on systems with musl

src/if-linux.c
The RA times are [provided in milliseconds](https://tools.ietf.org/html/rfc4861#section-4.2), but commit 569051c8aa8fc297eb8edb7bd228e0fd353d30c1 (dhcpcd-8.1.3~18) “Linux: prefer ms RA times” incorrectly scaled them by an extra factor of 1000 before writing them to `retrans_time_ms` and `base_reachable_time_ms`. Instead, write the values in milliseconds directly to the `*_ms` files, and correctly convert to jiffies or seconds for the other files if necessary.
Fixes NixOS/nixpkgs#76710.
=> Linux: fix RA time unit confusion

src/if-bsd.c
Shortly after dhcpcd started using these constants, they were dropped from OpenBSD kernel headers as they're only used by rad(8). Switch to dhcpcd's own constants instead, fixing build on recent -current.
=> use TEMP_PREFERRED/VALID_LIFETIME for OpenBSD

src/if-options.c
After an update I noticed that dhcpcd reported an error "controlgroup: wheel: not found". Looking into the code it seems that this is due to the new privsep code not moving /etc/group in the chroot. This patch is a quick fix for the error that simply checks if control_group was already parsed successfully.
Here is what the error looked like on my machine:
```
[root@light ~]# dhcpcd wlp3s0
dhcpcd-9.0.2 starting
controlgroup: wheel: not found
wlp3s0: connected to Access Point `Maison'
...
```
=> Do not report an error if control_group is already set

src/dhcp-common.c, src/dhcpcd.conf.5.in
Resolves
```
$ dhcpcd --nooption nd_prefix_information
unknown option `nd_prefix_information'
```
See commit message for details
=> Fix neighbor discovery option parsing

src/if-linux.c
skip netns if either "st_dev" or "st_ino" not matching.
=> fix if_getnetworknamespace matching bug.

src/dhcpcd.c
Since version 9.3.3 and commit a5348dd02c86fa940cd93f203d0aa974cae0563c, build without fork or signals fails on:
```
dhcpcd.c: In function ‘main’:
dhcpcd.c:2261:3: error: label ‘start_master’ used but not defined
goto start_master;
^~~~
```
=> src/dhcpcd.c: fix build without fork or signals

src/privsep-linux.c
```
^~~~~
```
It should be noted that `AUDIT_ARCH_NDS32` is only defined since kernel 5.2 and https://github.com/torvalds/linux/commit/fa562447e154334523daa44c0b60625d71a345f5
Fixes:
- http://autobuild.buildroot.org/results/af8ba07ea0c12ab8cd24d528ef98db05521f3d36
=> src/privsep-linux.c: add support for nds32

src/privsep-linux.c
```
^~~~~
```
It should be noted that `AUDIT_ARCH_XTENSA` is only defined since kernel 5.0 and https://github.com/torvalds/linux/commit/98c3115a4ec56f03056efd9295e0fcb4c5c57a85
=>  src/privsep-linux.c: add support for xtensa

src/privsep-linux.c
```
^~~~~
```
It should be noted that `AUDIT_ARCH_NIOS2` is only defined since kernel 5.2 and https://github.com/torvalds/linux/commit/1660aac45e5b49a5ace29fb5b73254617533fcbd
=>  src/privsep-linux.c: add support for nios2

src/privsep-linux.c
```
^~~~~
```
It should be noted that `AUDIT_ARCH_MICROBLAZE` is only defined since kernel 3.18 and https://github.com/torvalds/linux/commit/ce5d112827e5c2e9864323d0efd7ec2a62c6dce0
=>  src/privsep-linux.c: add support for microblaze

src/privsep-linux.c
```
^~~~~
```
It should be noted that `AUDIT_ARCH_{SH,SHEL,SH64,SHEL64}` are defined at least since kernel 3.7 and https://github.com/torvalds/linux/commit/607ca46e97a1b6594b29647d98a32d545c24bdff
=> src/privsep-linux.c: add support for sh

src/privsep-linux.c
```
privsep-linux.c:203: warning: "AUDIT_ARCH_SPARC64" redefined
203 | #    define AUDIT_ARCH_SPARC64
|
In file included from privsep-linux.c:35:
/srv/storage/autobuild/run/instance-0/output-1/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/linux/audit.h:392: note: this is the location of the previous definition
392 | #define AUDIT_ARCH_SPARC64 (EM_SPARCV9|__AUDIT_ARCH_64BIT)
|
privsep-linux.c:215:38: error: 'SECCOMP_AUDIT_ARCH' undeclared here (not in a function); did you mean 'SECCOMP_ALLOW_ARG'?
215 |  BPF_JUMP(BPF_JMP + BPF_JEQ + BPF_K, SECCOMP_AUDIT_ARCH, 1, 0),
|                                      ^~~~~~~~~~~~~~~~~~
```
=> src/privsep-linux: fix build on sparc

src/privsep-linux.c
```
^~~~~
```
It should be noted that AUDIT_ARCH_OPENRISC is defined since kernel 3.7: https://github.com/torvalds/linux/commit/e2bebb4ae6d9ac4ffc524db67f7ecb205a173f77
=> src/privsep-linux.c: add support for or1k

src/privsep-linux.c
```
^~~~~
```
It should be noted that `AUDIT_ARCH_{ARCOMPACT,ARCV2}` is only defined since kernel 5.2 and https://github.com/torvalds/linux/commit/67f2a8a29311841ba6ab9b0e2d1b8f1e9978cd84
Detection of arc compact and arc v2 have been "copy/pasted" from https://github.com/wbx-github/uclibc-ng/commit/afab56958f1cbb47b831ee3ebff231dfbae74af2
Fixes:
- http://autobuild.buildroot.org/results/d29083700a80dd647621eed06faeeae03f0587d3 …
=> src/privsep-linux.c: add support for arc

src/privsep-linux.c
=> src/privsep-linux.c: add support for m68k

configure
Same as https://github.com/linux-pam/linux-pam/pull/311 and https://github.com/karelzak/util-linux/pull/1216.
I had `test: too many arguments` when building dhcpcd using [sbase](https://core.suckless.org/sbase/).
Please check that I broke nothing.
Thank you.
=> configure: test -a|o is not POSIX

src/if-options.c
This affects the parsing of strings containing hex or octal escapes.
Prior to this change, if parameter `sbuf` was `NULL`, it would miscalculate the length of the string `l`. Eg `"test\x31"` or `"test\0061"` would be calculated as length 4.
=> Fix parsing of hex/octal escapes in strings

src/dhcpcd.8.in, src/dhcpcd.conf.5.in
In commit 3547ed19, the default metric offsets were changed. This PR updates the man pages accordingly.
=> Update man pages for default metric changes

src/if-bsd.c
The FreeBSD epair(4) interface type can be thought of as a virtual patch cable.
The epair interfaces come in pairs, with network traffic being passed between the 2 pairs.
The basic intent is to provide connectivity between two virtual network stack instances.
This interface type does not typically require an IP address, as it is passing traffic
between other virtual networks/interfaces which obtain their own IP address.
Therefore, add this interface type to the list that will be ignored by dhcpcd.
=> Add epair(4) to the ignored interface types list

src/if-options.c
"hostname" argument (-h) is a simple string and should never be
interpreted as a hex string.  It is also kept as a null terminated
string, so when we parse something that is meant to be null terminated
string do not attempt to parse it as a HW addressa.  The same applies to
"script" (-c) argument.
Signed-off-by: Andrzej Ostruszka <amo@semihalf.com>
=> Fix handling of hostname argument

src/dhcp.c
Applying [change from dhcpcd-9](https://github.com/NetworkConfiguration/dhcpcd/commit/63eacc1a92bac298e1069516dab7b305db70a208) to dhcpcd-8, which is the version in current use for RPi bullseye. 
I'm submitting this as a Draft Pull Request pending a build & test on my RPi 3B+. This may take a while due to my lack of experience :)  If you maintainers are more confident than I, please don't wait on me. I've been put in the position of a "`inform` option Evangelist", and I need to get this working! 
```
$ dhcpcd --version
dhcpcd 8.1.2
Copyright (c) 2006-2019 Roy Marples
Compiled in features: INET ARP ARPing IPv4LL INET6 DHCPv6 AUTH
```
=> Update ver 8 dhcp.c to Fix infinite INFORM messages 

src/privsep-linux.c
LoongArch is a new instruction set of Loongson 3A5000 CPU, you can read the [documents](https://github.com/loongson/LoongArch-Documentation) to get more infomation.
This PR add support for the LoongArch architecture, please review, thanks.
=> add support for loongarch64

hooks/dhcpcd-run-hooks.in
dhcpcd-run-hooks is intended to skip hooks with filenames ending in `~`, but the test only works if `$skip_hooks` is defined and not empty.  Refactor the test such that files ending in `~` are always skipped, as appears to be the intent of this code.
Fixes #112
=> Always skip hooks ending in ~

src/dhcp.c
Fix for #160 
Detecting host routes based on address comparison is not needed in classless routes as /32 mask can be explicitly used. This detecting mechanism did cause issues when gateway was set to 0.0.0.0 (link local routes).
=> dhcp: Fix classless link local static routes

src/ipv6nd.c
The __CTASSERT within ND_OPT_DNSSL is incorrectly referencing nd_opt_rdnss instead of nd_opt_dnss.
The error was undetected until now because both are equal in size...
=> Fix incorrect CTASSERT in ND_OPT_DNSSL

src/privsep-linux.c
Behavior: When dhcpcd runs on the ppc64le platform, it would be killed by SIGSYS.
After enabling seccomp debug in privsep-linux, the SIGSYS signal handler shows us the arch is ppc64 not ppc64le, so add ppc64le support in privsep-linux.c
Thanks.
=> privsep-linux: fix SECCOMP_AUDIT_ARCH missing ppc64le

README.md
Fixes the two rotten links reported in #202
=> chore: Link to GitHub for the updated commit log

src/dhcpcd-definitions.conf
DDoS Open Threat Signaling (DOTS) Agent Discovery, RFC8973
DHCP option 147,147; DHCPv6 option 141,142
Captive Portal, RFC8910
DHCP option 114; DHCVv6 option 104
update to attribution for MUD URL - RFC8520
=> Additional DHCP options

src/if-linux.c
Hi!
This is nothing significant, but rather a slight annoyance.
When using dhcpcd on risc-v, You get the error "dhcp_vendor: Invalid argument", investigating further I saw that the mproc string used by if_machinearch is defined as NULL under risc-v, which makes it fail, Im not entirly sure what exact info needs to be returned since some arches have the model, some have the vendor and some have the mmu, etc, so I decided to use uarch since it contains both a model and a vendor name, in case that is not ideal here is other variables that could be used
isa : rv64imafdc
mmu : sv39
uarch : sifive,u74-mc
(reference star64 sbc running Linux-5.15.107)
=> risc-v fix vendor error

compat/arc4random_uniform.c, compat/pidfile.c, compat/rb.c, compat/strlcpy.c
Here is a set of small compat syncs. None of them should make a functional difference, most actually just adjust comments.
I was reviewing them and checking that they aren't missing any fixes so I thought I might as well just sync them while I'm there.
One thing missing here is arc4random.c which seems to have diverged quite a bit from all shipped versions. Would there be interest in having that synced to an upstream version too or is there a reason for the divergence?
=> compat sync

src/dhcp.c
Check if state->bpf is allocated before attempting to write there.
=> Do not crash on dhcpcd test run

src/dhcpcd.c
Read can return up to `BUFSIZ` bytes. If that happens we zero `log[BUFSIZ]` which is outside the buffer. Found with a long error message and `-fsanitize=address`.
=> dhcpcd: Fix off-by-one overflow when read() writes full BUFSIZ

src/privsep.c
When running our Ubuntu tests with libc6 and strlcpy overflow checks enabled we found that the wrong size is passed to strlcpy resulting in a crash because of an overflow.
For context, here is the test run log: https://autopkgtest.ubuntu.com/results/autopkgtest-mantic/mantic/amd64/d/dhcpcd/20230814_101551_01fd7@/log.gz
And the stack trace from my manual run:
```
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
Download failed: Invalid argument.  Continuing without source file ./nptl/./nptl/pthread_kill.c.
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1 …
```
=> privsep: fix strlcpy overflow in psp_ifname

.github/workflows/build.yml
As the title says this will make the CI runner execute the tests in `tests/` after each build. OpenBSD needs a ulimit bump to avoid a `too many open files` error in `eloop-bench`.
=> ci: execute tests after successful build

compat/crypt_openssl/hmac.c, compat/crypt_openssl/hmac.h, compat/crypt_openssl/sha256.c, compat/crypt_openssl/sha256.h, configure, src/dhcpcd.c, tests/crypt/Makefile, tests/crypt/run-test.c, tests/crypt/test.h, tests/crypt/test_sha256.c
In a recent security review for the Ubuntu package of dhcpcd we found that the packaged version uses the built-in crypto primitives from `compat/crypt`.
We try to keep the number of low-level crypto implementations at a minimum to make it easier for the Ubuntu security team to review them, track eventual bugs as and ensure compliance in certified environments.
This PR adds alternative `compat/crypt` wrappers based on libcrypto and some tests to make sure they work correctly. I made sure that they also work  across different OpenSSL versions and with LibreSSL.
=> Support libcrypto for hmac and sha256

src/dhcp6.c
Fixes issue #246 
The payload of the prefix exclude option was correctly created but the amount of bytes to send in the DHCPv6 request was always set to 0 which resulted in an invalid prefix exclude option
This patch fixes this behavior by calculating the correct amount of bytes to send.
=> Send correct amount of used buffer for prefix exclude option

compat/arc4random.c, tests/eloop-bench/Makefile
With the recent OpenSSL addition we can now also use it in a few other places for convenience.
One useful thing it implements is portable high quality entropy generation. We can use it as a replacement for `/dev/urandom` to seed `arc4random()` where it is available.
=> compat: use OpenSSL RAND_priv_bytes() for entropy

src/privsep-linux.c
The issue occured while compiled by musl:
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = ?
+++ killed by SIGSYS +++
This patchs allows seccomp to make __NR_mmap2 syscall.
=> privsep: allow __NR_mmap2 call

compat/arc4random.c
Use `memset` instead of `explicit_bzero` to avoid the following build failure with uclibc-ng since version 10.0.3 and
https://github.com/NetworkConfiguration/dhcpcd/commit/837d09e34c487edaa92aa2ae71a630d84c927f8e:
```
/home/fabrice/buildroot/output/host/lib/gcc/arm-buildroot-linux-uclibcgnueabi/12.3.0/../../../../arm-buildroot-linux-uclibcgnueabi/bin/ld: ../compat/arc4random.o: in function `_rs_stir_if_needed':
arc4random.c:(.text+0x8cc): undefined reference to `explicit_bzero'
```
=> compat/arc4random.c: use memset instead of explicit_bzero

src/arp.c, src/dhcpcd.conf.5.in, src/if-options.c, src/if-options.h
RFC 5227 recommends 3 ways to deal with address conflict detection. 
a) Stop everything.
b) Defend and then stop on fail - this is what dhcpcd currently does.
c) Notify and carry on.
The current change implements the option c. A new option arp_persistdefence has been added and when this is enabled, the a defence is attempted upon a conflict and when that fails, an error is logged on every other conflict within the DEFEND_INTERVAL and the current IP address is retained.
=> dhcpcd: Add support for arp persist defence

src/dhcp.c
dhcp_handlebootp handled zero sized packets correctly, but dhcp_redirect_dhcp did not have such protection. Move size check before both of them. Size when called from dhcp_packet is checked by is_packet_udp_bootp call. Only dhcp_recvmsg needs earlier checking to be added.
Fixes #283
=> Move dhcp(v4) packet size check earlier

src/ipv6.c, src/ipv6nd.c, src/ipv6nd.h, src/sa.c, src/sa.h
Resolves issue #102.
Implement RFC4191 support for Route Information options in Router Advertisements.  This option allows a router to provide routes for a specific prefix instead of only providing default routes.
My use case is that I have a ULA network with a VPN router and no IPv6 internet access.  Using this router as the default route does not work well because the host then thinks it can reach the Internet.  By instead advertising a route just for the ULA prefix hosts will immediately know they cannot reach the Internet through this router.
I've tested this PR in a VM in this exact configuration and it seems to work quite well.  I changed the radvd config on the fly to remove and add the route and it behaved as expected.
=> add RFC4191 support

src/dhcp.c
Current IPv6_PREFERRED_ONLY (option 108) handling code is only effective when current state is DHS_DISCOVER or DHS_REBOOT. However the assumption that we'll only receive OFFER and ACK with option 108 in those two states is not true. Particularly, when we receive multiple ACKs upon our REQUEST, the first ACK will trigger the use_v6only code path and dhcp_drop() us into DHS_NONE state, therefore the option 108 on second ACK won't be handled correctly and we'll bind to the lease incorrectly.
DHS_NONE is not the only possible state, considering the corner cases of server configuration change and multiple servers. Thus we should just remove the state check here.
=> dhcpcd: Respect IPV6_PREFERRED_ONLY flag regardless of state

src/dhcpcd-definitions.conf
https://datatracker.ietf.org/doc/html/rfc2132#section-3.4
time_offset (dhcp v4 option 2) should be int32, not uint32, as it can indicate a time offset east (positive) or west (negative) of zero meridian.
Fixes issue #318
=> Fix time_offset to be int to match RFC-2132

hooks/30-hostname.in
If the hostname is already set before dhcpcd is started, `need_hostname` will hit the "No old hostname" case and will call `false` to return 1. `set_hostname` will return with the same return value. Then `30-hostname` will exit with the same exit value:
```
dhcpcd-10.0.6 starting
dev: loaded udev
DUID 00:03:00:01:3c:97:0e:e9:32:3c
enp0s25: IAID 0e:e9:32:3c
enp0s25: soliciting a DHCP lease
enp0s25: offered 192.168.3.61 from 192.168.1.7
enp0s25: ignoring offer of 192.168.3.61 from 192.168.1.8
enp0s25: probing address 192.168.3.61/20
enp0s25: leased 192.168.3.61 for 3600 seconds
enp0s25: adding route to 192.168.0.0/20
enp0s25: adding default route via 192.168.1.1
script_status: /usr/lib/dhcpcd/dhcpcd-run-hooks: WEXITSTATUS 1
exiting due to oneshot
dhcpcd exited
```
Return with value 0 in …
=> hooks/30-hostname: Exit with 0 if setting hostname is not needed

src/ipv4ll.c
When IPv4LL address conflict is detected, it is failed to restart IPv4LL
since IPv4LL is running. The commit fixes the problem by restarting ARP
probing instead of restarting IPv4LL.
=> IPv4LL: Restart ARP probling on address conflict

src/dhcp.c
According to RFC8925 section 3.3.1, when the server supports both option 108 (IPv6-Only Preferred) and option 116 (Auto-Configure), and the client only sends IPv6-Only Preferred option, then the server SHOULD return 0.0.0.0 as the offered address, and not setting the Auto-Configure option.
However, in our current client code, the IPv6-Only Preferred option in a 0.0.0.0 OFFER is only handled correctly when the Auto-Configure option is present. This patch fixes this issue.
=> DHCP: Handle option 108 correctly when receiving 0.0.0.0 OFFER

src/dhcp-common.h, src/dhcp.c, src/if-options.c, src/if.c, src/if.h, src/ipv4.h
We've been enforcing an interface MTU that is slightly larger than the minimum for some time.
Instead, log an error than the MTU is smaller than the minimum to send a BOOTP message.
The DHCP MTU is only used when adding routes as setting the interface MTU can cause a PHY reset which is bad.
Fixes #345
=> DHCP: No longer set interface mtu

src/dhcp.c
RFC8925 mentions "The client MUST ignore the IPv6-Only Preferred option if the length field value is not 4."
=> dhcp: get_option_uint32/16 only accept options with correct len

src/if-linux.c
Since we are capturing packets at L2 we should not be using ETH_DATA_LEN but ETH_FRAME_LEN to include also dst/src MAC and EtherType.
=> Include frame header in buffer length

src/dhcp-common.c, src/dhcpcd.c, src/script.c
Running dhpcd --dumplease with input from stdin and redirecting stdout to a file outputs nothing to the output. The reason is that printf / fprintf is used to write the output but it is not explicitly flushed when done, or before exiting, and stdout to files is fully buffered by default while stdout to terminals is line buffered by default.
This adds calls to fflush() at the end of dhcp_print_option_encoding() and script_dump(), plus one just before exiting dhcpcd.
=> dhcpcd: stdout output sometimes empty when redirected to a file

hooks/dhcpcd-run-hooks.8.in, src/dhcp6.c, src/dhcpcd.conf.5.in
If no response is received to Confirm messages, instead of failing, go ahead and use the lease, as recommended by RFC 8415 18.2.3.
=> Apply lastlease behavior to DHCPv6

src/if-linux.c
I'm using ipv6 source-based routing on a machine with multiple WANs.  I'm adding routes for each delegated subnet to their respective WAN interface, eg:
```
default from <DELEGATED-SUBNET> via <GATEWAY> dev <WAN-DEV> ...
```
However, dhcpcd on the WAN doesn't parse the RTA_SRC route attribute, so it adds the route to it's internal kernel route list as the "default route" - the net effect being that if the upstream router removes and adds back the real default route (eg. ISP goes down momentarily), dhcpcd will think these source-routes are existing kernel default routes, and won't add the new default route back.
This simple pull request patches if-linux.c to parse the RTA_SRC attribute for a "specified" route and ignores the route, after which dhcpcd behaves correctly.
I haven't modified …
=> dhcpcd not ignoring source-based routes on linux

src/dhcp6.c
If lastlease is enabled, and dhcpcd is unable to confirm its prior lease, after timeout, don't continue to solicit. Confine lastlease behavior to only the CONFIRM state.
This cleans up some minor issues with the initial commit for DHCPv6 lastlease.
=> DHCP6: lastlease behavior after Confim non-response

src/ipv6.c
In certain instances, `ifp->if_data[IF_DATA_IPV6]` was not yet initialized when ipv6_addaddr adds the address to the state, and a segfault would ensue. Mitigate this by ensuring the state is initialized when adding the addresses.
fixes #394
=> IPv6: Avoid uninitialized ifp state when adding address

hooks/50-timesyncd.conf
Exit the timesyncd hook immediately if not running on a systemd host AND timesyncd is not executable.
=> Exit the timesyncd hook if not on systemd and not executable (#398)

src/common.c, src/common.h, src/if-linux.c, src/ipv6.c, src/route.h
Sends route lifetime to NETLINK RTA_EXPIRES
Partially addresses #428
Still need to send hoplimit
=> Add route lifetime from Router Advertisement

src/if-bsd.c
=> revert e3c5de1

src/dhcp.c, src/dhcp6.c, src/if-options.c, src/if-options.h
As it's outlined in #328, using multiple enterprise IDs with vendclass overwrites all previous values.
This fixes the malformation of the DHCPv4 packet and adds support for multiple different enterprise ID vendclass options.
=> Fix using multiple enterprise IDs with vendclass (Option 124 DHCP / Option 16 DHCPv6) (#328)

src/if-linux.c, src/ipv6.c, src/route.c, src/route.h
If a route gets an update (say from an RA), consider it changed so new expiry gets pushed out to system.
Resolves #428
=> Update route if acquired time changes

src/dhcp6.c
RFC8415 says client must always request Information Request refresh time option 32.
Client has other logic for handling if server does not include this in the reply.
Resolves #445
=> Always send req for InfoRefreshTime option on Inform-Req

src/if-options.c, src/if-options.h
Remove arbitrary limit, raising to the maximum representable by uint8
As discussed in https://github.com/NetworkConfiguration/dhcpcd/discussions/435
=> Increase max IPv4 clientid.

src/dhcp.c
If "noipv4ll" configured, do not drop IPv4 link local addresses from interface.
Resolves #462
=> Only drop IPv4 LL addresses if configured to handle them

src/dhcp.c
850f93b changed the logic while moving things around. Restore the original logic so we open a socket even if the address is the same, so long as it's the first time.
Fixes: #501
=> Restore logic on when to open an address specific socket

src/if-linux.c
As discussed in #504 , this fixes a DHCP issue when the WAN interface rename, left `/etc/resolv.conf` empty. The change updates `if-linux.c` to stop the old interface (`ifp->name`) and start the new one (`ifn`)
=> [Fix] DHCP Failure on WAN Interface Rename (Fixes #504)
